version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.5
      environment:
        JOBS: 1
  working_directory: ~/jslib.k6.io

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/jslib.k6.io
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "supported.json" }}
      - run:
          name: "Install k6"
          command: |
            curl -fsSL https://github.com/loadimpact/k6/releases/download/v0.36.0/k6-v0.36.0-linux-amd64.tar.gz | tar -xvz
            mv k6-*/k6 ~/jslib.k6.io/k6
      - save_cache:
          key: v1-dependency-cache-{{ checksum "supported.json" }}
          paths:
            - k6
      - persist_to_workspace:
          root: ~/jslib.k6.io
          paths:
            - .

  test-extended:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/jslib.k6.io
      - run:
          name: Run tests
          command: ~/jslib.k6.io/k6 run tests/testSuite.js

  test-base:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/jslib.k6.io
      - run:
          name: Run tests with compatibility-mode=base
          command: ~/jslib.k6.io/k6 run --compatibility-mode=base tests/testSuiteBase.js

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/jslib.k6.io
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy lib to s3
          command: ~/jslib.k6.io/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test-extended:
          requires:
            - build
      - test-base:
          requires:
            - build
      - deploy:
          requires:
            - test-extended
            - test-base
          filters:
            branches:
              only: master
